# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b73273f67377237f2a8be4bf0105be57159b50f8c2ee94a851e66881636ef7a5f3718034a1a5390c0c8d9aa0cc347dc881e77aa5ee094cefed9ca1f0144e32bb

test:
  secret_key_base: 2ff3be08412288829733885916abd890ea1b30d2c77e1037b075f646751e81f7ae0fae438096f4033b2d0b1b9e7ab6a7bc142b73a7c8b9d3f783b7da0fd07a75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
